name: google_maps_flutter_example
description: Demonstrates how to use the google_maps_flutter plugin.
publish_to: none

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.5.0
  google_maps_flutter_platform_interface: ^2.4.0

dev_dependencies:
  build_runner: ^2.1.10
  espresso: ^0.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
