# Generated by Django 2.2.5 on 2019-09-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='User name')),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
